repos:
-   repo: https://github.com/psf/black
    rev: '24.10.0'
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/PyCQA/flake8
    rev: '7.1.1'
    hooks:
    -   id: flake8
        args: ['--max-line-length=88', '--extend-ignore=E203,E501,W503', '--exclude=.venv']
-   repo: https://github.com/PyCQA/isort
    rev: '5.13.2'
    hooks:
    -   id: isort
        args: ['--profile=black']
- repo: https://github.com/kynan/nbstripout
  rev: 0.8.1
  hooks:
    - id: nbstripout
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.8.1
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v5.0.0'
    hooks:
    -   id: check-ast
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.0'  # add version here
    hooks:
        - id: poetry-export
          args: ["-f", "requirements.txt", "--without-hashes", "-o", "requirements.txt"]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.13.0'  # Use the sha / tag you want to point at
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
