# Contributors
Shuang Song:
  email: "songshgeo@mail.bnu.edu.cn"
  institution: "Beijing Normal University"
  address: "No.19, Xinjiekouwai St. Haidian District, Beijing"
  country: "China"
  contribution: "The originator."
