
# The background figure of repo
fig@background: "![background](https://gitee.com/SongshGeo/Picgo2/raw/master/uPic/background.jpeg)"

# author profiles.
github@songshgeo: "[my GitHub](https://github.com/SongshGeo)"
researchgate@songshgeo: "https://www.researchgate.net/profile/Shuang-Song-14"
